FROM docker.io/alpine:3

COPY --from=ghcr.io/larsks/s-nail-builder:main /usr/local/bin/mail /usr/local/bin/

RUN apk add \
  bash \
  dash \
  ca-certificates \
  sqlite \
  curl \
  git \
  jq \
  openvi \
  ed \
  tzdata \
  less

  COPY etc/* /etc/
