#!/bin/bash

set -e

READ_SOCK=/bbs-sock/api-read.sock

list_pools() {
  if ! curl -Ssf --unix-socket "$READ_SOCK" http://localhost/exam/questions | jq -r '.[]'; then
    echo "ERROR: Failed to read list of pools." >&2
    exit 1
  fi
}

available_pools="$(list_pools | tr '\n' ',')"

while getopts l ch; do
  case $ch in
  l)
    list_pools
    exit
    ;;
  \?)
    exit 2
    ;;
  esac
done

pool=$1
if [[ -z "$pool" ]]; then
  echo "You must specify the name of a question pool ($available_pools)." >&2
  exit 1
fi

qid=$2

if [[ -z "$qid" ]]; then
  if ! question=$(curl -Ssf --unix-socket "$READ_SOCK" "http://localhost/exam/questions/$pool"); then
    echo "ERROR: Failed to get a question from pool $pool. Available pools are $available_pools."
    exit 1
  fi
else
  if ! question=$(curl -Ssf --unix-socket "$READ_SOCK" "http://localhost/exam/questions/$pool/${qid^^}"); then
    echo "ERROR: Failed to get question $qId from pool $pool." >&2
    exit 1
  fi
fi

qId=$(jq -r .id <<<"$question")
qQuestion=$(jq -r .question <<<"$question")
qAnswer=$(jq -r .correct_letter <<<"$question")

cat <<EOF
Question $qId
===============

$(fmt -w70 <<<"$qQuestion")

EOF

letters=ABCD
i=0
jq -r '.answers[]' <<<"$question" |
  while read -r answer; do
    echo "${letters:$i:1}. $answer" | fmt -w 70 | sed '2,$s/^/   /'
    ((++i))
  done

echo

while :; do
  printf "Your answer? "
  read -r answer
  if [[ ${answer^^} =~ ^["${letters}"]$ ]]; then
    break
  elif [[ ${answer^^} = Q ]]; then
    exit
  fi
done

echo

if [[ ${answer^^} = "${qAnswer^^}" ]]; then
  printf "That's correct! Great work.\n"
else
  printf "The correct answer was %s.\n" "$qAnswer"
fi

echo
